adding a merged report with yml file

diff --git a/.github/workflows/merged_reports.yml b/.github/workflows/merged_reports.yml
--- a/.github/workflows/merged_reports.yml
+++ b/.github/workflows/merged_reports.yml
@@ -11,6 +11,10 @@ on:
         description: 'iOS Run ID'
         required: true
         type: string
+      manual_run_id:
+        description: 'iOS Run ID'
+        required: true
+        type: string
 
 jobs:
   merge-and-report:
@@ -20,6 +24,8 @@ jobs:
       ANDROID_ARTIFACT: android-serenity-json
       IOS_RUN_ID: ${{ inputs.ios_run_id }}
       IOS_ARTIFACT: ios-serenity-json
+      MANUAL_RUN_ID: ${{ inputs.manual_run_id }}
+      MANUAL_ARTIFACT: manual-serenity-json
 
     steps:
       - name: Checkout repository
@@ -50,6 +56,19 @@ jobs:
             -o ios_json.zip \
             https://api.github.com/repos/${{ github.repository }}/actions/artifacts/$ARTIFACT_ID/zip
           unzip ios_json.zip -d ios-json
+
+      - name: Download manual Serenity JSON
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
+            https://api.github.com/repos/${{ github.repository }}/actions/runs/$MANUAL_RUN_ID/artifacts > manual_artifacts.json
+          ARTIFACT_ID=$(jq -r --arg NAME "$MANUAL_ARTIFACT" '.artifacts[] | select(.name==$NAME) | .id' manual_artifacts.json)
+          [ -z "$ARTIFACT_ID" ] && echo "iOS JSON artifact not found!" && exit 1
+          curl -L -H "Authorization: Bearer $GITHUB_TOKEN" \
+            -o manual_json.zip \
+            https://api.github.com/repos/${{ github.repository }}/actions/artifacts/$ARTIFACT_ID/zip
+          unzip manual_json.zip -d manual-json
 
       - name: Merge Serenity JSONs
         run: |
